package net.skidcode.gh.twilightforest.entity.render;

import net.minecraft.client.model.ModelPart;
import net.minecraft.client.render.entity.model.QuadrupedEntityModel;

public class ModelTwilightDeer
extends QuadrupedEntityModel {
    public ModelPart horn1a;
    public ModelPart horn1b;
    public ModelPart horn1c;
    public ModelPart horn1d;
    public ModelPart horn1e;
    public ModelPart horn1f;
    public ModelPart horn1g;
    public ModelPart horn1h;
    public ModelPart horn1i;
    public ModelPart horn1j;
    public ModelPart horn1k;
    public ModelPart horn2a;
    public ModelPart horn2b;
    public ModelPart horn2c;
    public ModelPart horn2d;
    public ModelPart horn2e;
    public ModelPart horn2f;
    public ModelPart horn2g;
    public ModelPart horn2h;
    public ModelPart horn2i;
    public ModelPart horn2j;
    public ModelPart horn2k;
    public ModelPart neck;
    public ModelPart nose;

    public ModelTwilightDeer() {
        super(12, 0.0f);
        this.head = new ModelPart(0, 5);
        this.head.addCuboid(-2.0f, -8.0f, -6.0f, 4, 6, 6, 0.0f);
        this.head.setPivot(0.0f, 4.0f, -7.0f);
        this.body = new ModelPart(36, 6);
        this.body.addCuboid(-4.0f, -10.0f, -7.0f, 6, 18, 8, 0.0f);
        this.body.setPivot(1.0f, 5.0f, 2.0f);
        this.body.pitch = 1.570796f;
        this.rightHindLeg = new ModelPart(0, 17);
        this.rightHindLeg.addCuboid(-3.0f, 0.0f, -2.0f, 2, 12, 3, 0.0f);
        this.rightHindLeg.setPivot(0.0f, 12.0f, 9.0f);
        this.leftHindLeg = new ModelPart(0, 17);
        this.leftHindLeg.addCuboid(-1.0f, 0.0f, -2.0f, 2, 12, 3, 0.0f);
        this.leftHindLeg.setPivot(2.0f, 12.0f, 9.0f);
        this.rightFrontLeg = new ModelPart(0, 17);
        this.rightFrontLeg.addCuboid(-3.0f, 0.0f, -3.0f, 2, 12, 3, 0.0f);
        this.rightFrontLeg.setPivot(0.0f, 12.0f, -5.0f);
        this.leftFrontLeg = new ModelPart(0, 17);
        this.leftFrontLeg.addCuboid(-1.0f, 0.0f, -3.0f, 2, 12, 3, 0.0f);
        this.leftFrontLeg.setPivot(2.0f, 12.0f, -5.0f);
        this.neck = new ModelPart(10, 19);
        this.neck.addCuboid(-2.5f, -8.0f, -11.0f, 3, 9, 4, 0.0f);
        this.neck.setPivot(1.0f, 5.0f, 2.0f);
        this.neck.pitch = 0.2443461f;
        this.nose = new ModelPart(52, 0);
        this.nose.addCuboid(-1.5f, -5.0f, -9.0f, 3, 3, 3, 0.0f);
        this.nose.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1a = new ModelPart(20, 0);
        this.horn1a.addCuboid(-3.0f, -10.0f, -2.0f, 2, 2, 2, 0.0f);
        this.horn1a.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1b = new ModelPart(20, 0);
        this.horn1b.addCuboid(-4.0f, -10.0f, -1.0f, 1, 1, 3, 0.0f);
        this.horn1b.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1c = new ModelPart(20, 0);
        this.horn1c.addCuboid(-5.0f, -11.0f, 1.0f, 1, 1, 5, 0.0f);
        this.horn1c.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1d = new ModelPart(20, 0);
        this.horn1d.addCuboid(-5.0f, -14.0f, 2.0f, 1, 4, 1, 0.0f);
        this.horn1d.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1e = new ModelPart(21, 0);
        this.horn1e.addCuboid(-6.0f, -17.0f, 3.0f, 1, 4, 1, 0.0f);
        this.horn1e.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1f = new ModelPart(20, 0);
        this.horn1f.addCuboid(-6.0f, -13.0f, 0.0f, 1, 1, 3, 0.0f);
        this.horn1f.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1g = new ModelPart(20, 0);
        this.horn1g.addCuboid(-6.0f, -14.0f, -3.0f, 1, 1, 4, 0.0f);
        this.horn1g.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1h = new ModelPart(21, 0);
        this.horn1h.addCuboid(-7.0f, -15.0f, -6.0f, 1, 1, 4, 0.0f);
        this.horn1h.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1i = new ModelPart(20, 0);
        this.horn1i.addCuboid(-6.0f, -16.0f, -9.0f, 1, 1, 4, 0.0f);
        this.horn1i.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1j = new ModelPart(25, 0);
        this.horn1j.addCuboid(-7.0f, -18.0f, -1.0f, 1, 5, 1, 0.0f);
        this.horn1j.setPivot(0.0f, 4.0f, -7.0f);
        this.horn1k = new ModelPart(28, 0);
        this.horn1k.addCuboid(-6.0f, -19.0f, -6.0f, 1, 5, 1, 0.0f);
        this.horn1k.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2a = new ModelPart(20, 0);
        this.horn2a.addCuboid(1.0f, -10.0f, -2.0f, 2, 2, 2, 0.0f);
        this.horn2a.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2b = new ModelPart(20, 0);
        this.horn2b.addCuboid(3.0f, -10.0f, -1.0f, 1, 1, 3, 0.0f);
        this.horn2b.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2c = new ModelPart(20, 0);
        this.horn2c.addCuboid(4.0f, -11.0f, 1.0f, 1, 1, 5, 0.0f);
        this.horn2c.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2d = new ModelPart(20, 0);
        this.horn2d.addCuboid(4.0f, -14.0f, 2.0f, 1, 4, 1, 0.0f);
        this.horn2d.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2e = new ModelPart(21, 0);
        this.horn2e.addCuboid(5.0f, -17.0f, 3.0f, 1, 4, 1, 0.0f);
        this.horn2e.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2f = new ModelPart(20, 0);
        this.horn2f.addCuboid(5.0f, -13.0f, 0.0f, 1, 1, 3, 0.0f);
        this.horn2f.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2g = new ModelPart(20, 0);
        this.horn2g.addCuboid(5.0f, -14.0f, -3.0f, 1, 1, 4, 0.0f);
        this.horn2g.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2h = new ModelPart(21, 0);
        this.horn2h.addCuboid(6.0f, -15.0f, -6.0f, 1, 1, 4, 0.0f);
        this.horn2h.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2i = new ModelPart(20, 0);
        this.horn2i.addCuboid(5.0f, -16.0f, -9.0f, 1, 1, 4, 0.0f);
        this.horn2i.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2j = new ModelPart(25, 0);
        this.horn2j.addCuboid(6.0f, -18.0f, -1.0f, 1, 5, 1, 0.0f);
        this.horn2j.setPivot(0.0f, 4.0f, -7.0f);
        this.horn2k = new ModelPart(28, 0);
        this.horn2k.addCuboid(5.0f, -19.0f, -6.0f, 1, 5, 1, 0.0f);
        this.horn2k.setPivot(0.0f, 4.0f, -7.0f);
    }

    @Override
    public void render(float limbAngle, float limbDistance, float animationProgress, float headYaw, float headPitch, float scale) {
        super.render(limbAngle, limbDistance, animationProgress, headYaw, headPitch, scale);
        this.setAngles(limbAngle, limbDistance, animationProgress, headYaw, headPitch, scale);
        this.neck.render(scale);
        this.nose.render(scale);
        this.horn1a.render(scale);
        this.horn1b.render(scale);
        this.horn1c.render(scale);
        this.horn1d.render(scale);
        this.horn1e.render(scale);
        this.horn1f.render(scale);
        this.horn1g.render(scale);
        this.horn1h.render(scale);
        this.horn1i.render(scale);
        this.horn1j.render(scale);
        this.horn1k.render(scale);
        this.horn2a.render(scale);
        this.horn2b.render(scale);
        this.horn2c.render(scale);
        this.horn2d.render(scale);
        this.horn2e.render(scale);
        this.horn2f.render(scale);
        this.horn2g.render(scale);
        this.horn2h.render(scale);
        this.horn2i.render(scale);
        this.horn2j.render(scale);
        this.horn2k.render(scale);
    }

    @Override
    public void setAngles(float limbAngle, float limbDistance, float animationProgress, float headYaw, float headPitch, float scale) {
        super.setAngles(limbAngle, limbDistance, animationProgress, headYaw, headPitch, scale);
        this.horn1a.yaw = this.head.yaw;
        this.horn1a.pitch = this.head.pitch;
        this.horn1b.yaw = this.head.yaw;
        this.horn1b.pitch = this.head.pitch;
        this.horn1c.yaw = this.head.yaw;
        this.horn1c.pitch = this.head.pitch;
        this.horn1d.yaw = this.head.yaw;
        this.horn1d.pitch = this.head.pitch;
        this.horn1e.yaw = this.head.yaw;
        this.horn1e.pitch = this.head.pitch;
        this.horn1f.yaw = this.head.yaw;
        this.horn1f.pitch = this.head.pitch;
        this.horn1g.yaw = this.head.yaw;
        this.horn1g.pitch = this.head.pitch;
        this.horn1h.yaw = this.head.yaw;
        this.horn1h.pitch = this.head.pitch;
        this.horn1i.yaw = this.head.yaw;
        this.horn1i.pitch = this.head.pitch;
        this.horn1j.yaw = this.head.yaw;
        this.horn1j.pitch = this.head.pitch;
        this.horn1k.yaw = this.head.yaw;
        this.horn1k.pitch = this.head.pitch;
        this.horn2a.yaw = this.head.yaw;
        this.horn2a.pitch = this.head.pitch;
        this.horn2b.yaw = this.head.yaw;
        this.horn2b.pitch = this.head.pitch;
        this.horn2c.yaw = this.head.yaw;
        this.horn2c.pitch = this.head.pitch;
        this.horn2d.yaw = this.head.yaw;
        this.horn2d.pitch = this.head.pitch;
        this.horn2e.yaw = this.head.yaw;
        this.horn2e.pitch = this.head.pitch;
        this.horn2f.yaw = this.head.yaw;
        this.horn2f.pitch = this.head.pitch;
        this.horn2g.yaw = this.head.yaw;
        this.horn2g.pitch = this.head.pitch;
        this.horn2h.yaw = this.head.yaw;
        this.horn2h.pitch = this.head.pitch;
        this.horn2i.yaw = this.head.yaw;
        this.horn2i.pitch = this.head.pitch;
        this.horn2j.yaw = this.head.yaw;
        this.horn2j.pitch = this.head.pitch;
        this.horn2k.yaw = this.head.yaw;
        this.horn2k.pitch = this.head.pitch;
        this.nose.yaw = this.head.yaw;
        this.nose.pitch = this.head.pitch;
    }
}