package net.skidcode.gh.twilightforest.dimension.feature;

import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.class_104;
import net.minecraft.world.World;

public class TFGenWitchHut
extends TFGenerator {
    @Override
    public boolean method_1142(World world, Random rand, int x, int y, int z) {
        return this.generateTinyHut(world, rand, x, y, z);
    }

    public boolean generateTinyHut(World world, Random rand, int x, int y, int z) {
        this.worldObj = world;
        if (!this.isAreaClear(world, rand, x, y, z, 5, 7, 6)) {
            return false;
        }
        this.putBlock(x + 1, y + 0, z + 1, this.randStone(rand, 1), true);
        this.putBlock(x + 2, y + 0, z + 1, this.randStone(rand, 1), true);
        this.putBlock(x + 3, y + 0, z + 1, this.randStone(rand, 1), true);
        this.putBlock(x + 5, y + 0, z + 1, this.randStone(rand, 1), true);
        this.putBlock(x + 0, y + 0, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 0, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 0, z + 2, this.randStone(rand, 1), true);
        this.putBlock(x + 0, y + 0, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 0, z + 3, this.randStone(rand, 1), true);
        this.putBlock(x + 0, y + 0, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 0, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 0, z + 4, this.randStone(rand, 1), true);
        this.putBlock(x + 1, y + 0, z + 5, this.randStone(rand, 1), true);
        this.putBlock(x + 2, y + 0, z + 5, this.randStone(rand, 1), true);
        this.putBlock(x + 3, y + 0, z + 5, this.randStone(rand, 1), true);
        this.putBlock(x + 5, y + 0, z + 5, this.randStone(rand, 1), true);
        this.putBlock(x + 1, y + 1, z + 1, this.randStone(rand, 2), true);
        this.putBlock(x + 3, y + 1, z + 1, this.randStone(rand, 2), true);
        this.putBlock(x + 5, y + 1, z + 1, this.randStone(rand, 2), true);
        this.putBlock(x + 0, y + 1, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 1, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 1, z + 2, this.randStone(rand, 2), true);
        this.putBlock(x + 0, y + 1, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 0, y + 1, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 1, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 1, z + 4, this.randStone(rand, 2), true);
        this.putBlock(x + 1, y + 1, z + 5, this.randStone(rand, 2), true);
        this.putBlock(x + 3, y + 1, z + 5, this.randStone(rand, 2), true);
        this.putBlock(x + 5, y + 1, z + 5, this.randStone(rand, 2), true);
        this.putBlock(x + 1, y + 2, z + 1, this.randStone(rand, 3), true);
        this.putBlock(x + 2, y + 2, z + 1, this.randStone(rand, 3), true);
        this.putBlock(x + 3, y + 2, z + 1, this.randStone(rand, 3), true);
        this.putBlock(x + 4, y + 2, z + 1, this.randStone(rand, 3), true);
        this.putBlock(x + 5, y + 2, z + 1, this.randStone(rand, 3), true);
        this.putBlock(x + 0, y + 2, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 2, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 2, z + 2, this.randStone(rand, 3), true);
        this.putBlock(x + 0, y + 2, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 2, z + 3, this.randStone(rand, 3), true);
        this.putBlock(x + 0, y + 2, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 1, y + 2, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 5, y + 2, z + 4, this.randStone(rand, 1), true);
        this.putBlock(x + 1, y + 2, z + 5, this.randStone(rand, 3), true);
        this.putBlock(x + 2, y + 2, z + 5, this.randStone(rand, 3), true);
        this.putBlock(x + 3, y + 2, z + 5, this.randStone(rand, 3), true);
        this.putBlock(x + 4, y + 2, z + 5, this.randStone(rand, 3), true);
        this.putBlock(x + 5, y + 2, z + 5, this.randStone(rand, 3), true);
        this.putBlock(x + 0, y + 3, z + 2, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 0, y + 3, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 0, y + 3, z + 4, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 2, y + 3, z + 1, this.randStone(rand, 4), true);
        this.putBlock(x + 3, y + 3, z + 1, this.randStone(rand, 4), true);
        this.putBlock(x + 4, y + 3, z + 1, this.randStone(rand, 4), true);
        this.putBlock(x + 2, y + 3, z + 5, this.randStone(rand, 4), true);
        this.putBlock(x + 3, y + 3, z + 5, this.randStone(rand, 4), true);
        this.putBlock(x + 4, y + 3, z + 5, this.randStone(rand, 4), true);
        this.putBlock(x + 0, y + 4, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 3, y + 4, z + 1, this.randStone(rand, 5), true);
        this.putBlock(x + 3, y + 4, z + 5, this.randStone(rand, 5), true);
        this.putBlock(x + 0, y + 5, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlock(x + 0, y + 6, z + 3, (byte)Block.BRICKS.id, true);
        this.putBlockAndMetadata(x + 0, y + 2, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 0, y + 2, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 0, y + 2, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 0, y + 2, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 3, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 6, y + 2, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 3, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 3, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 3, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 4, z + 0, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 3, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 4, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 1, y + 4, z + 6, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 4, z + 0, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 3, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 4, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 5, y + 4, z + 6, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 5, z + 0, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 5, z + 1, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 5, z + 0, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 5, z + 1, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 2, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 3, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 4, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 5, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 5, z + 5, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 2, y + 5, z + 6, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 5, z + 5, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 4, y + 5, z + 6, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 0, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 1, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 2, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 4, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 5, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 6, z + 6, (byte)Block.DOUBLE_SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 7, z + 0, (byte)Block.SLAB.id, 2, true);
        this.putBlockAndMetadata(x + 3, y + 7, z + 6, (byte)Block.SLAB.id, 2, true);
        this.putBlock(x + 1, y - 1, z + 3, (byte)Block.NETHERRACK.id, true);
        this.putBlock(x + 1, y + 0, z + 3, (byte)Block.FIRE.id, true);
        this.worldObj.setBlock(x + 3, y + 1, z + 3, Block.SPAWNER.id);
        class_104 ms = (class_104)world.method_1777(x + 3, y + 1, z + 3);
        ms.method_2035("Skeleton");
        return true;
    }
}